# Generated by Django 3.0.2 on 2020-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='thumbnail',
            new_name='thumb',
        ),
    ]
